### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by qqxze** [nudtnlp/tianchi-nl2sql-top1#3]
您好，请问您这边计划公开代码嘛

**Comment by nudtnlp** [comment]
感谢您的关注，代码暂时不开，谢谢！

**Comment by qqxze** [comment]
好的 谢谢啦




------------------ 原始邮件 ------------------
发件人: "NUDT NLP"<notifications@github.com>;
发送时间: 2019年10月17日(星期四) 上午8:59
收件人: "nudtnlp/tianchi-nl2sql-top1"<tianchi-nl2sql-top1@noreply.github.com>;
抄送: "朱琪超"<839983653@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nudtnlp/tianchi-nl2sql-top1] 代码 (#3)




感谢您的关注，代码暂时不开，谢谢！
